version: '3.9'

services:
  app:
    container_name: nest-app
    build:
      context: .
    restart: unless-stopped
    networks:
      - test
    env_file: .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - test
    depends_on:
      - app

networks:
  test:
